spring:
  application:
    name: FileManager
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/file_manager
    username: file_manager
    password: file_manager
  messages:
    basename: i18n/messages
  thymeleaf:
    enabled: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true
  task:
    execution:
      thread-name-prefix: file-manager-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: file-manager-scheduling-
      pool:
        size: 2

logging:
  level:
    ROOT: INFO
    tech.przybysz.pms.filemanager: DEBUG

server:
  port: 8082

storage:
  location: /home/andprz/storage
  backup:
    execute: true
    locations: ["/media/andprz/External HDD/storage"]
    mode: STRICT
    copies-count: 1
